before_install:
- export TZ=Asia/Taipei

language: ruby

rvm:
- 2.6.3

services:
  - postgresql

addons:
  postgresql: "11.4"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
- bundle install --jobs=3 --retry=3
- bundle exec rails db:migrate
- rspec spec/features