language: ruby

rvm:
- 2.6.3

services:
  - postgresql

addons:
  postgresql: "11.4"

script:
- bundle install --jobs=3 --retry=3
- bundle exec rails db:migrate
- rspec

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres